# 默认配置
default:
  # 群聊中所有消息冷却时间，单位秒,0则无限制
  GroupCD: 0
  # 群聊中 每个人的消息冷却时间，单位秒，0则无限制。注意，开启后所有消息都会进CD，无论是否触发插件。
  GroupUserCD: 1
  # 机器人响应模式，0-所有 1-仅@机器人 2-仅回应主人 3-仅回应前缀 4-前缀或@机器人 5-主人无前缀，群员前缀或@机器人
  mode: 0

  # 机器人前缀 设置后前缀+指令触发机器人
  alias:
    - karin

  # 白名单插件、功能，只有在白名单中的插件、功能才会响应
  enable: []

  # 黑名单插件、功能，黑名单中的插件、功能不会响应
  disable: []
