name: Issue Welcome

on:
  issues:
    types: [opened]

jobs:
  issue-welcome:
    runs-on: ubuntu-latest
    steps:
      - name: welcome
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'welcome'
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œæˆ‘ä»¬æ³¨æ„åˆ°ä½ æ˜¯ä¸€æ¬¡åˆ›å»ºé—®é¢˜ï¼Œæ„Ÿè°¢ä½ çš„åŠ å…¥ï¼æˆ‘ä»¬éå¸¸æœŸå¾…ä½ çš„æƒ³æ³•å’Œè´¡çŒ®ã€‚ğŸŒŸ
          issue-emoji: 'eyes'